# Tutorial 1: Ring Tensor
在该计算库中，所使用的基础数据结构是```RingTensor```，它表示的是环上的张量，对应于```torch```的tensor，将tensor转化到我们所需要使用的环上并进行运算，可支持```torch```的多种数据类型（int64, int32, float64, float32）
现在从导入RingTensor包开始

In [41]:
from crypto.tensor.RingTensor import RingTensor
import torch

### Conversion between torch tensors and RingTensor
该计算库提供了一个```convert_to_ring```的方法，可以将torch.Tensor类型的张量数据转换到环上。```convert_to_real_field```方法可以将一个RingTensor数据转换为torch.Tensor类型
该计算库支持```torch.int64```,```torch.int32```,```torch.float64```和```torch.float32```类型的数据转换至环上

In [42]:
# Create torch tensor
x = torch.tensor([1.0, 2.0, 3.0])

# Convert a tensor to ring
x_on_ring = RingTensor.convert_to_ring(x)
print(x_on_ring)

# Convert a RingTensor to real field
x_real_field = x_on_ring.convert_to_real_field()
print(x_real_field)

[RingTensor
 value:tensor([ 65536, 131072, 196608], device='cuda:0') 
 dtype:float 
 scale:65536]
tensor([1., 2., 3.], device='cuda:0')


该计算库支持```torch.int64```,```torch.int32```,```torch.float64```和```torch.float32```类型的数据转换至环上

In [43]:
# Convert different data type tensor to ring
# torch.int64
x_int64 = torch.tensor([1, 2, 3], dtype=torch.int64)

x_int64_on_ring = RingTensor.convert_to_ring(x_int64)
print(x_int64_on_ring)

# torch.int32
x_int32 = torch.tensor([1, 2, 3], dtype=torch.int32)

x_int32_on_ring = RingTensor.convert_to_ring(x_int32)
print(x_int32_on_ring)

# torch.float64
x_float64 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

x_float64_on_ring = RingTensor.convert_to_ring(x_float64)
print(x_float64_on_ring)

# torch.float32
x_float32 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

x_float32_on_ring = RingTensor.convert_to_ring(x_float32)
print(x_float32_on_ring)

[RingTensor
 value:tensor([1, 2, 3], device='cuda:0') 
 dtype:int 
 scale:1]
[RingTensor
 value:tensor([1, 2, 3], device='cuda:0') 
 dtype:int 
 scale:1]
[RingTensor
 value:tensor([ 65536, 131072, 196608], device='cuda:0') 
 dtype:float 
 scale:65536]
[RingTensor
 value:tensor([ 65536, 131072, 196608], device='cuda:0') 
 dtype:float 
 scale:65536]


## Operations on Ring tensor
Now let's look at what we can do with our ```RingTensor```

#### Arithmetic Operations
We can carry out regular arithmetic operations between ```RingTensors```. These operations return a ring tensor output.

In [44]:
# Arithmetic operations between RingTensors
x_on_ring = RingTensor.convert_to_ring(torch.tensor([1.0, 2.0, 3.0]))

y_on_ring = RingTensor.convert_to_ring(torch.tensor([2.0]))


# Addition
res_on_ring = x_on_ring + y_on_ring
print("\nAddition:", res_on_ring.convert_to_real_field())

# Subtraction
res_on_ring = x_on_ring - y_on_ring
print("\nSubtraction", res_on_ring.convert_to_real_field())

# Multiplication
res_on_ring = x_on_ring * y_on_ring
print("\nMultiplication", res_on_ring.convert_to_real_field())

# Matrix Multiplication
y_on_ring = RingTensor.convert_to_ring(torch.tensor([[1.0], [2.0], [3.0]]))
res_on_ring = x_on_ring @ y_on_ring
print("\nMatrix Multiplication", res_on_ring.convert_to_real_field())


Addition: tensor([3., 4., 5.], device='cuda:0')

Subtraction tensor([-1.,  0.,  1.], device='cuda:0')

Multiplication tensor([2., 4., 6.], device='cuda:0')

Matrix Multiplication tensor([14.], device='cuda:0')


#### Comparisons
Similarly, we can compute element-wise comparisons on ```RingTensors```. Different from arithmetic operations, comparisons performed on ```RingTensors``` will return ```True``` or ```False```, which is like comparisons between ```torch``` tensors.

In [45]:
#Comparisons between RingTensors
x_on_ring = RingTensor.convert_to_ring(torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0]))

y_on_ring = RingTensor.convert_to_ring(torch.tensor([5.0, 4.0, 3.0, 2.0, 1.0]))

# Less than
result = x_on_ring < y_on_ring
print("\n(x < y) :", result)

# Less than or equal
result = x_on_ring <= y_on_ring
print("\n(x <= y) :", result)

# Greater than
result = x_on_ring > y_on_ring
print("\n(x > y) :", result)

# Greater than or equal
result = x_on_ring >= y_on_ring
print("\n(x >= y) :", result)

# Equal
result = x_on_ring == y_on_ring
print("\n(x == y) :", result)

# Not Equal
result = x_on_ring != y_on_ring
print("\n(x != y) :", result)


(x < y) : tensor([ True,  True, False, False, False], device='cuda:0')

(x <= y) : tensor([ True,  True,  True, False, False], device='cuda:0')

(x > y) : tensor([False, False, False,  True,  True], device='cuda:0')

(x >= y) : tensor([False, False,  True,  True,  True], device='cuda:0')

(x == y) : tensor([False, False,  True, False, False], device='cuda:0')

(x != y) : tensor([ True,  True, False,  True,  True], device='cuda:0')


#### Other operations
该计算库也支持对```torch```tensor进行的一些其他操作，比如对RingTensor进行reshape, stack, cat, unsqueeze等操作， 和tensor不同的是，RingTensor的stack, cat是在一个RingTensor的基础上拼接其他的RingTensor。

In [46]:
x_on_ring = RingTensor.convert_to_ring(torch.tensor([1.0, 2.0, 3.0]))
y_on_ring = RingTensor.convert_to_ring(torch.tensor([4.0, 5.0, 6.0]))

# Concatenation
res_on_ring = x_on_ring.cat(y_on_ring)
print("Concatenation: \n", res_on_ring.convert_to_real_field())

# Stacking
res_on_ring = x_on_ring.stack(y_on_ring)
print("\nConcatenation: \n", res_on_ring.convert_to_real_field())

# Reshaping
res_on_ring_after_reshape = res_on_ring.reshape(-1, 6)
print("\nReshape: \n", res_on_ring_after_reshape.convert_to_real_field())

# UnSqueezing
res_on_ring = x_on_ring.unsqueeze(dim=1)
print("\nUnSqueezing: \n", res_on_ring.convert_to_real_field())

Concatenation: 
 tensor([1., 2., 3., 4., 5., 6.], device='cuda:0')

Concatenation: 
 tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')

Reshape: 
 tensor([[1., 2., 3., 4., 5., 6.]], device='cuda:0')

UnSqueezing: 
 tensor([[1.],
        [2.],
        [3.]], device='cuda:0')
